run-20250919_014643-4pydaazr/logs/debug-internal.log